const VEHICLE_CATALOG = [
  {
    id: 'ford_mustang_gt',
    brand: 'Ford',
    model: 'Mustang GT',
    name: 'Ford Mustang GT',
    type: 'Performance coupe',
    aliases: ['ford mustang', 'mustang', 'mustang gt', 'gt mustang'],
    imageUrl: 'https://images.unsplash.com/photo-1561535743-c82c241502d5?auto=format&fit=crop&q=90&w=1600',
    sourceUrl: 'https://www.altayermotors.com/ford/',
    highlight: 'Iconic V8 coupe with strong emotional appeal and accessible performance.',
    specs: {
      Engine: '5.0L V8, approx. 480+ hp',
      Power: 'Approx. 480+ hp',
      Drivetrain: 'Rear-wheel drive, automatic or manual by trim',
      'Top speed': '250-290 km/h approx.',
      '0-100 km/h': '4.3s approx.',
      'Estimated price': 'AED 255,000-280,000 approx.',
      Character: 'Muscle coupe, emotional sound, strong daily usability',
      'Best fit': 'Performance coupe buyer wanting V8 theatre and value',
    },
  },
  {
    id: 'jaguar_f_pace',
    brand: 'Jaguar',
    model: 'F-Pace',
    name: 'Jaguar F-Pace',
    type: 'Luxury performance SUV',
    aliases: ['jaguar', 'jaguar f-pace', 'jaguar f pace', 'f-pace', 'f pace'],
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=90&w=1600',
    sourceUrl: 'https://www.altayermotors.com/jaguar/',
    highlight: 'British luxury SUV with a sportier road feel and premium cabin presence.',
    specs: {
      Engine: 'Petrol, mild-hybrid options by trim',
      Power: 'Approx. 246-542 hp by trim',
      Drivetrain: 'All-wheel drive by most regional trims',
      'Top speed': 'Approx. 217-286 km/h by trim',
      '0-100 km/h': 'Approx. 4.0-7.3s by trim',
      'Estimated price': 'AED 290,000-520,000 approx.',
      Character: 'Sport-luxury SUV with British design and road presence',
      'Best fit': 'Luxury SUV buyer wanting British sport character',
    },
  },
  {
    id: 'land_rover_defender',
    brand: 'Land Rover',
    model: 'Defender',
    name: 'Land Rover Defender',
    type: 'Luxury 4x4',
    aliases: ['land rover', 'defender', 'land rover defender'],
    imageUrl: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=90&w=1600',
    sourceUrl: 'https://www.altayermotors.com/land-rover/',
    highlight: 'Iconic luxury 4x4 with real all-terrain credibility.',
    specs: {
      Engine: 'Petrol mild-hybrid options by trim',
      Power: 'Approx. 296-518 hp by trim',
      Drivetrain: 'All-wheel drive with terrain systems',
      'Top speed': 'Approx. 191-240 km/h by trim',
      '0-100 km/h': 'Approx. 5.2-8.0s by trim',
      'Estimated price': 'AED 280,000-650,000 approx.',
      Character: 'Iconic luxury 4x4 with serious off-road credibility',
      'Best fit': 'Premium off-road capability with iconic design',
    },
  },
  {
    id: 'maserati_mc20',
    brand: 'Maserati',
    model: 'MC20',
    name: 'Maserati MC20',
    type: 'Italian supercar',
    aliases: ['maserati', 'mc20', 'maserati mc20'],
    imageUrl: 'https://images.unsplash.com/photo-1756548843479-3783100b3447?auto=format&fit=crop&q=90&w=1600',
    sourceUrl: 'https://www.altayermotors.com/maserati/',
    highlight: 'Mid-engine Italian supercar with exotic theatre and rarity.',
    specs: {
      Engine: '3.0L twin-turbo Nettuno V6',
      Power: 'Approx. 621 hp',
      Drivetrain: 'Rear-wheel drive, dual-clutch transmission',
      'Top speed': '325 km/h approx.',
      '0-100 km/h': '2.9s approx.',
      'Estimated price': 'AED 1.1M-1.4M approx.',
      Character: 'Mid-engine Italian supercar with exotic theatre',
      'Best fit': 'Exotic supercar client wanting Italian rarity',
    },
  },
  {
    id: 'ferrari_296_gtb',
    brand: 'Ferrari',
    model: '296 GTB',
    name: 'Ferrari 296 GTB',
    type: 'Hybrid supercar',
    aliases: ['ferrari', '296', '296 gtb', 'ferrari 296', 'ferrari 296 gtb'],
    imageUrl: 'https://images.unsplash.com/photo-1556516731-779d3492975b?auto=format&fit=crop&q=90&w=1600',
    sourceUrl: 'https://www.altayermotors.com/ferrari/',
    highlight: 'Compact Ferrari hybrid performance with intense emotional pull.',
    specs: {
      Engine: 'V6 plug-in hybrid, 800+ hp combined',
      Power: 'Approx. 819 hp combined',
      Drivetrain: 'Rear-wheel drive hybrid supercar',
      'Top speed': '330 km/h approx.',
      '0-100 km/h': '2.9s approx.',
      'Estimated price': 'AED 1.4M-1.8M approx.',
      Character: 'Ferrari hybrid performance with compact supercar agility',
      'Best fit': 'Ferrari hybrid performance and emotional ownership',
    },
  },
];

const SOURCE_REGISTRY = [
  { brand: 'Ford', url: 'https://www.altayermotors.com/ford/' },
  { brand: 'Jaguar', url: 'https://www.altayermotors.com/jaguar/' },
  { brand: 'Land Rover', url: 'https://www.altayermotors.com/land-rover/' },
  { brand: 'Maserati', url: 'https://www.altayermotors.com/maserati/' },
  { brand: 'Ferrari', url: 'https://www.altayermotors.com/ferrari/' },
];

const SHOWROOM_MODELS = VEHICLE_CATALOG.map((vehicle, index, list) => ({
  brand: vehicle.brand,
  model: vehicle.model,
  type: vehicle.type,
  detail: vehicle.highlight,
  imageUrl: vehicle.imageUrl,
  comparePrompt: `Compare ${vehicle.name} and ${list[(index + 1) % list.length].name}`,
}));

module.exports = {
  SOURCE_REGISTRY,
  SHOWROOM_MODELS,
  VEHICLE_CATALOG,
};
